# Generated by Django 4.2.1 on 2023-05-27 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AnikeAPI', '0004_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='category_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='AnikeAPI.category'),
        ),
    ]
