# Generated by Django 4.2.1 on 2023-05-27 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AnikeAPI', '0005_menuitem_category_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='category_id',
            new_name='category',
        ),
    ]
